### ISSUE TITLE
Authentication failures due to Steam changes

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/bitlbee-steam#74]
Valve has recently modified the WebAPI, which has broken user authentication.  Any users who have already obtained a `token` and `sessid` should be good for now.  However, any users who are attempting to newly authenticate will likely run into issues.  The changes do not look super significant, and the plugin should be able to be patched fairly easily.

On a side note, it appears these changes are making way for two-factor authentication (not SteamGuard).  The changes seem to be incomplete as there are missing error messages, and some other quarks.  Moreover, the functionality has yet to be seen in the actual Steam client.  As a result, I suspect things will be breaking frequently over the next month.

**Comment by DamonGant** [comment]
Can confirm signing in is broken

    @root | steam - Logging in: Requesting authentication token
    @root | steam - Login error: Failed to obtain OAuth data
    @root | steam - Logging in: Signing off.

**Comment by swmarc** [comment]
Same here:

@nick | account steam set authcode XXXXX
@root | steam - Logging in: Connecting
@root | steam - Logging in: Requesting authentication key
@root | authcode = `XXXXX'
@root | steam - Logging in: Requesting authentication token
@root | steam - Login error: Failed to obtain OAuth data
@root | steam - Logging in: Signing off..

**Comment by jgeboski** [comment]
Sorry for the delay!  I have been slammed with school work.  I will try and get this fixed soon.  I may have some time tomorrow evening to patch this issue.

**Comment by jgeboski** [comment]
I pushed a patch to `development` which should address this issue.  Please test.

**Comment by swmarc** [comment]
Unfortunately it still doesn't work, but the reply changed now to

@root | steam - Login error: Incorrect login.

after using the "set authcode" command.

**Comment by jgeboski** [comment]
Try removing the account and readding it.  Also, ensure your username and password are correct.

**Comment by subnomo** [comment]
I am still getting the same error as before:
```
@root | steam - Logging in: Requesting authentication token
@root | steam - Login error: Failed to obtain OAuth data
@root | steam - Logging in: Signing off.
```

**Comment by jgeboski** [comment]
@subnomo Did you build the `development` branch?

**Comment by Luminaz** [comment]
It's working for me, Thanks !

**Comment by subnomo** [comment]
@jgeboski I realize now that I hadn't completely remove the old version of `bitlbee-steam`. It works now, thanks for the fix!

**Comment by swmarc** [comment]
@jgeboski Perfect. Re-adding the account worked.

Thanks.

**Comment by jgeboski** [comment]
Merged to `master`.

**Comment by sfauzia** [comment]
I'm experiencing this issue again with the latest release 1.3.0. I've tried deleting my account in irssi and adding it again, but I keep getting `steam - Login error: Failed to obtain OAuth data` after entering my verification code with `account steam set authcode`. Any ideas as to why? I was getting an error of 'not being able to obtain extra user information' prior to the update, but it had been working perfectly a few days before that. Steam web works perfectly and I'm not a limited steam user.

Running bitlee-steam on bitlbee version 3.4 on ArchLinux. If there's any other information I can provide, please let me know.

**Comment by adnandzebic** [comment]
I'm also experiencing the same issue with weechat.

**Comment by jgeboski** [comment]
Someone, please, open a new issue.
