### ISSUE TITLE
Login error: Failed to obtain OAuth data

### ISSUE THREAD

**Issue by sfauzia** [jgeboski/bitlbee-steam#90]
Running the latest version of bitlbee-steam 1.3 with bitlbee ver 3.4 and irssi ver 0.8.17 on ArchLinux, I'm running into the issue that I can no longer authenticate my steam account. I deleted my account and re-added it in the hopes of resolving the issue (as recommended in a [similar](https://github.com/jgeboski/bitlbee-steam/issues/74#issuecomment-131156780) report by a user), to no avail.

This is what I obtain:

    <@root> steam - Logging in: Connecting
    <@root> steam - Logging in: Requesting authentication key
    <@root> authcode = `D2HFC'
    <@root> steam - Logging in: Requesting authentication token
    <@root> steam - Login error: Failed to obtain OAuth data
    <@root> steam - Logging in: Signing off..

Prior to the update I was having an issue obtaining "extra user information", so I updated hoping to resolve that, but now I have this issue.

Looking at my bitlbee logs, my connection issues began 12 August. From my logs:

    <@root> steam - Login error: Failed to obtain extra user information
    <@root> steam - Logging in: Signing off..
    <@root> steam - Logging in: Reconnecting in 5 seconds..

And it never reconnected. Post updating to 1.3 (the next day, 13 August) the sole error is the aforementioned one with OAuth.

Looking at my package manager logs, on the night of the 11th/12th, I upgraded from 1.2.0.r10.g81c86de-1 -> 1.2.0.r12.gf558aaf-1. And my issues with logging in only started post this update. Though that's no longer the relevant issue I thought to mention this just in case.

If there's any more information I may provide, please let me know.

**Comment by jgeboski** [comment]
Looks like there was an API change.  I will try to get a fix out ASAP.

**Comment by gdude2002** [comment]
Damn it ValvE, why not make it easy for people to use your services for once..

Although come to mention it, steam is /really/ patchy for me, maybe they're doing some infrastructure/service upgrades

**Comment by jgeboski** [comment]
I have this patched locally, and I will push a patch tomorrow after more testing.

**Comment by jgeboski** [comment]
This has been fixed as of 485ee3d.

**Comment by sfauzia** [comment]
Thanks a lot, working perfectly! :)

**Comment by lrustand** [comment]
This still happens. I get the exact same errors described in the first post:
```
<@root> steam - Logging in: Connecting
<@root> steam - Logging in: Requesting authentication key
<@root> authcode = `8J5TV'
<@root> steam - Logging in: Requesting authentication token
<@root> steam - Login error: Failed to obtain OAuth data
<@root> steam - Logging in: Signing off..
```
